	-- This script was generated by the ERD tool in pgAdmin 4.
	-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
	BEGIN;
	
	
	CREATE TABLE IF NOT EXISTS public."Blood_screen"
	(
	    "Blood_Screen_ID" serial NOT NULL,
	    "Result" character varying(200) COLLATE pg_catalog."default" NOT NULL,
	    "Blood_Type" character varying(50) COLLATE pg_catalog."default" NOT NULL,
	    "Donation_ID" integer NOT NULL,
	    CONSTRAINT "Blood_screen_pkey" PRIMARY KEY ("Blood_Screen_ID")
	);
	
	CREATE TABLE IF NOT EXISTS public."Donation"
	(
	    "Donation_ID" serial NOT NULL,
	    "Blood_Amount" integer NOT NULL,
	    "Donation_Time" integer NOT NULL,
	    CONSTRAINT "Donation_pkey" PRIMARY KEY ("Donation_ID")
	);
	
	CREATE TABLE IF NOT EXISTS public."Registration"
	(
	    "Registration_ID" serial NOT NULL,
	    "Doctor_ID" integer NOT NULL,
	    "Donor_ID" integer NOT NULL,
	    "Donation_ID" integer NOT NULL,
	    "Date" date NOT NULL,
	    CONSTRAINT "Registration_pkey" PRIMARY KEY ("Registration_ID")
	);
	
	CREATE TABLE IF NOT EXISTS public."Doctor"
	(
	    "Doctor_ID" serial NOT NULL,
	    "Doctor_Name" character varying(50) COLLATE pg_catalog."default" NOT NULL,
	    "Experience" integer NOT NULL,
	    CONSTRAINT "Doctor_pkey" PRIMARY KEY ("Doctor_ID")
	);
	
	CREATE TABLE IF NOT EXISTS public."Donor"
	(
	    "Donor_ID" serial NOT NULL,
	    "Donor_Name" character varying(50) COLLATE pg_catalog."default" NOT NULL,
	    "Donor_Card" character varying(100) COLLATE pg_catalog."default" NOT NULL,
	    CONSTRAINT "Donor_pkey" PRIMARY KEY ("Donor_ID")
	);
	
	ALTER TABLE IF EXISTS public."Blood_screen"
	    ADD CONSTRAINT fk_donation_screen FOREIGN KEY ("Donation_ID")
	    REFERENCES public."Donation" ("Donation_ID") MATCH SIMPLE
	    ON UPDATE CASCADE
	    ON DELETE CASCADE;
	
	
	ALTER TABLE IF EXISTS public."Registration"
	    ADD CONSTRAINT fk_doctor FOREIGN KEY ("Doctor_ID")
	    REFERENCES public."Doctor" ("Doctor_ID") MATCH SIMPLE
	    ON UPDATE CASCADE
	    ON DELETE CASCADE;
	
	
	ALTER TABLE IF EXISTS public."Registration"
	    ADD CONSTRAINT fk_donation FOREIGN KEY ("Donation_ID")
	    REFERENCES public."Donation" ("Donation_ID") MATCH SIMPLE
	    ON UPDATE CASCADE
	    ON DELETE CASCADE;
	
	
	ALTER TABLE IF EXISTS public."Registration"
	    ADD CONSTRAINT fk_donor FOREIGN KEY ("Donor_ID")
	    REFERENCES public."Donor" ("Donor_ID") MATCH SIMPLE
	    ON UPDATE CASCADE
	    ON DELETE CASCADE;
	
	END;